########################################
# File:     Dockerfile
# Created:  8/17/2023
# By:       Kaleb C
########################################

FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive

########################################
# Install Tools
########################################

RUN apt-get update && apt-get install -yq --no-install-recommends\
    gcc\
    g++\
    make\
    cmake\
    build-essential\
    gdb\
    clang-14\
    clang-format-14\
    clang-tidy-14\
    lcov\
    libgtest-dev\
    python3\
    python3-pip\
    python-is-python3\
    less\
    sudo\
    curl\
    unzip\
    busybox\
    wget\
    iputils-ping\
    git\
    perl\
    file\
    locales\
    && apt-get clean && rm -rf /var/lib/apt/lists/*

########################################
# Generate Locale
########################################

RUN locale-gen --purge en_US.UTF-8

########################################
# Python Installs
########################################

RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir\
    bs4

########################################
# Copy bashrc
########################################

WORKDIR /root/
COPY generic.bashrc .bashrc

########################################